# Generated by Django 5.2.5 on 2025-08-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('step', models.IntegerField(default=1)),
                ('type', models.CharField(choices=[('CASH_IN', 'CASH_IN'), ('CASH_OUT', 'CASH_OUT'), ('DEBIT', 'DEBIT'), ('PAYMENT', 'PAYMENT'), ('TRANSFER', 'TRANSFER')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nameOrig', models.CharField(max_length=100)),
                ('oldbalanceOrg', models.DecimalField(decimal_places=2, max_digits=15)),
                ('newbalanceOrig', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nameDest', models.CharField(max_length=100)),
                ('oldbalanceDest', models.DecimalField(decimal_places=2, max_digits=15)),
                ('newbalanceDest', models.DecimalField(decimal_places=2, max_digits=15)),
                ('isFraud', models.BooleanField(default=False)),
                ('isFlaggedFraud', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
